# name: Frontend CI/CD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Set up Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18

#       - name: Install and build
#         run: |
#           npm ci
#           npm run build

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and push image
#         uses: docker/build-push-action@v5
#         with:
#           push: true
#           tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest

#       - name: Deploy to VM via SSH
#         uses: appleboy/ssh-action@v1.2.0
#         with:
#           host: ${{ secrets.VM_HOST }}
#           username: ${{ secrets.VM_USER }}
#           key: ${{ secrets.VM_SSH_KEY }}
#           script: |
#             docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
#             docker stop frontend || true
#             docker rm frontend || true
#             docker run -d -p 80:80 --name frontend ${{ secrets.DOCKER_USERNAME }}/frontend:latest



name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js for build
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install dependencies and build project
      - name: Install and build
        run: |
          npm ci
          npm run build

      # 4️⃣ Prepare Docker for image building
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6️⃣ Build and push Docker image to Docker Hub
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # 7️⃣ Deploy on your VM through SSH
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "🔄 Pulling latest Docker image..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest

            echo "🛑 Stopping old container if exists..."
            sudo docker stop frontend || true
            sudo docker rm frontend || true

            echo "🚀 Running new container on port 8080..."
            sudo docker run -d -p 8080:80 --name frontend ${{ secrets.DOCKER_USERNAME }}/frontend:latest

            echo "🧹 Cleaning up unused Docker images..."
            sudo docker system prune -f

      # 8️⃣ Verify deployment (health check)
      - name: Verify Deployment
        run: |
          echo "🔍 Checking if the app is live..."
          sleep 5
          curl -I http://${{ secrets.VM_HOST }}:8080 || exit 1
